---
- name: Deploy Blackbox Exporter with Multiple Endpoints
  hosts: all
  become: true
  vars:
    blackbox_enable_website_monitoring: true
    blackbox_endpoints:

  roles:
    - prometheus
    - blackbox_exporter 